config/routes.rb
Rails.application.routes.draw do

  namespace :api do
    get 'v1/index'
    post 'v1/login'
  end

  resources :articles do
    resources :comments
  end

  root 'events#index'
  
  resources :events
  devise_for :users, path: 'auth', path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :comments
  validates :title, presence: true,
  length: { minimum: 5 }
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    def index
        @articles = Article.all
    end

    def new
        @article = Article.new
    end
    
    def edit
        @article = Article.find(params[:id])
    end
   
    def create
        @article = Article.new(article_params)
        if @article.save
            redirect_to @article
          else
            render 'new'
        end
    end
    
    def show
        @article = Article.find(params[:id])
    end

    def update 
        @article = Article.find(params[:id])
        if @article.update(article_params)
            redirect_to @article
        else
            render 'edit'
        end
    end
    
    def destroy
        @article = Article.find(params[:id])
        @article.destroy
       
        redirect_to articles_path
    end

    private
    def article_params
    params.require(:article).permit(:title, :text, :content)
  
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= form_with model: @article, local: true do |form| %>
 
<% if @article.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@article.errors.count, "error") %> prohibited
      this article from being saved:
    </h2>
    <ul>
      <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<div class="hahaha">huhuhu</div>
<p>
  <%= form.label :title %><br>
  <%= form.text_field :title %>
</p>

<p>
  <%= form.label :text %><br>
  <%= form.text_area :text %>
</p>

<p>
  <%= form.submit %>
</p>

<% end %>

app/views/articles/edit.html.erb
<h1>Edit article</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h1>Listing articles</h1>

<table class="table"
  <tr>
    <th>Title</th>
    <th>Text</th>
  </tr>

  <% @articles.each do |article| %>
    <tr>
      <td>
        <%= article.title %>
      </td>
      <td>
        <%= article.text %>
      </td>
      <td>
        <%= link_to 'Show', article_path(article) %>
      </td>
      <td>
        <%= link_to 'Edit', edit_article_path(article) %>
      </td>
      <td>
        <%= link_to 'Destroy', article_path(article),
        method: :delete,
        data: { confirm: 'Are you sure?' } %>
      </td>
    </tr>
    <% end %>
</table>

app/views/articles/new.html.erb
<h1>New article</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>

<h2>Comments</h2>
<% @article.comments.each do |comment| %>
  <p>
    <strong>Commenter:</strong>
    <%= comment.commenter %>
  </p>

  <p>
    <strong>Comment:</strong>
    <%= comment.body %>
  </p>
<% end %>

<h2>Add a comment:</h2>
<%= form_with(model: [ @article, @article.comments.build ]) do |form| %>
  <p>
    <%= form.label :commenter %><br>
    <%= form.text_field :commenter %>
  </p>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>