config/routes.rb
Rails.application.routes.draw do

  namespace :api do
    get 'v1/index'
    post 'v1/login'
  end

  resources :articles do
    resources :comments
  end

  root 'events#index'
  
  resources :events
  devise_for :users, path: 'auth', path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/event.rb
class Event < ApplicationRecord
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json

  before_action :authenticate_user!
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:title, :nameEvent, :startDate, :endDate, :address, :latitude, :longitude, :nameUstad, :theame, :comment)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_with(model: event, local: true) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :event_title %>
  </div>

  <div class="field">
    <%= form.label :nameEvent %>
    <%= form.text_field :nameEvent, id: :event_nameEvent %>
  </div>

  <div class="field">
    <%= form.label :startDate %>
    <%= form.text_field :startDate, id: :event_startDate %>
  </div>

  <div class="field">
    <%= form.label :endDate %>
    <%= form.text_field :endDate, id: :event_endDate %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address, id: :event_address %>
  </div>

  <div class="field">
    <%= form.label :latitude %>
    <%= form.text_field :latitude, id: :event_latitude %>
  </div>

  <div class="field">
    <%= form.label :longitude %>
    <%= form.text_field :longitude, id: :event_longitude %>
  </div>

  <div class="field">
    <%= form.label :nameUstad %>
    <%= form.text_field :nameUstad, id: :event_nameUstad %>
  </div>

  <div class="field">
    <%= form.label :theame %>
    <%= form.text_field :theame, id: :event_theame %>
  </div>

  <div class="field">
    <%= form.label :comment %>
    <%= form.text_field :comment, id: :event_comment %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<p id="notice">
  <%= notice %>
</p>

<h1>Events</h1>
<button class="btn btn-primary" style="float:right; margin:6px; color: red;">
  <%= link_to 'New article', new_article_path %></button>
<div class="panel panel-primary">
  <!-- Default panel contents -->
  <div class="panel-heading">Panel heading</div>
  <div class="panel-body">
    <table class="table">
      <thead>
        <tr>
          <th>Title</th>
          <th>Nameevent</th>
          <th>Startdate</th>
          <th>Enddate</th>
          <th>Address</th>
          <th>Latitude</th>
          <th>Longitude</th>
          <th>Nameustad</th>
          <th>Theame</th>
          <th>Comment</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @events.each do |event| %>
          <tr>
            <td>
              <%= event.title %>
            </td>
            <td>
              <%= event.nameEvent %>
            </td>
            <td>
              <%= event.startDate %>
            </td>
            <td>
              <%= event.endDate %>
            </td>
            <td>
              <%= event.address %>
            </td>
            <td>
              <%= event.latitude %>
            </td>
            <td>
              <%= event.longitude %>
            </td>
            <td>
              <%= event.nameUstad %>
            </td>
            <td>
              <%= event.theame %>
            </td>
            <td>
              <%= event.comment %>
            </td>
            <td>
              <button class="btn btn-primary">
                <%= link_to 'Show', event %>
              </button>
            </td>
            <td>
              <%= link_to 'Edit', edit_event_path(event) %>
            </td>
            <td>
              <%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %>
            </td>
          </tr>
          <% end %>
      </tbody>
    </table>
  </div>
</div>
<br>
<h1>Hello, Rails!</h1>
<%= link_to 'My Blog', controller: 'articles' %><br>

<%= link_to 'New Event', new_event_path %>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @event.title %>
</p>

<p>
  <strong>Nameevent:</strong>
  <%= @event.nameEvent %>
</p>

<p>
  <strong>Startdate:</strong>
  <%= @event.startDate %>
</p>

<p>
  <strong>Enddate:</strong>
  <%= @event.endDate %>
</p>

<p>
  <strong>Address:</strong>
  <%= @event.address %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @event.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @event.longitude %>
</p>

<p>
  <strong>Nameustad:</strong>
  <%= @event.nameUstad %>
</p>

<p>
  <strong>Theame:</strong>
  <%= @event.theame %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @event.comment %>
</p>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>